name: 'Disable PR'

on:
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          close-pr: true
          lock-pr: true
          pr-comment: 'This repository does not accept pull requests.'
          process-only: 'prs'
